/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as authTermsRouteImport } from './routes/(auth)/terms'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authPrivacyRouteImport } from './routes/(auth)/privacy'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppProjectIndexRouteImport } from './routes/app/project/index'
import { Route as AppProjectListIndexRouteImport } from './routes/app/project-list/index'
import { Route as AppProjectProjectIdIndexRouteImport } from './routes/app/project/$projectId/index'
import { Route as AppProjectProjectIdTasksIndexRouteImport } from './routes/app/project/$projectId/tasks/index'
import { Route as AppProjectProjectIdBoardIndexRouteImport } from './routes/app/project/$projectId/board/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const authTermsRoute = authTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authPrivacyRoute = authPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AppProjectIndexRoute = AppProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectListIndexRoute = AppProjectListIndexRouteImport.update({
  id: '/project-list/',
  path: '/project-list/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectProjectIdIndexRoute =
  AppProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectProjectIdTasksIndexRoute =
  AppProjectProjectIdTasksIndexRouteImport.update({
    id: '/project/$projectId/tasks/',
    path: '/project/$projectId/tasks/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectProjectIdBoardIndexRoute =
  AppProjectProjectIdBoardIndexRouteImport.update({
    id: '/project/$projectId/board/',
    path: '/project/$projectId/board/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/privacy': typeof authPrivacyRoute
  '/register': typeof authRegisterRoute
  '/terms': typeof authTermsRoute
  '/app/': typeof AppIndexRoute
  '/app/project-list': typeof AppProjectListIndexRoute
  '/app/project': typeof AppProjectIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/board': typeof AppProjectProjectIdBoardIndexRoute
  '/app/project/$projectId/tasks': typeof AppProjectProjectIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/privacy': typeof authPrivacyRoute
  '/register': typeof authRegisterRoute
  '/terms': typeof authTermsRoute
  '/app': typeof AppIndexRoute
  '/app/project-list': typeof AppProjectListIndexRoute
  '/app/project': typeof AppProjectIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/board': typeof AppProjectProjectIdBoardIndexRoute
  '/app/project/$projectId/tasks': typeof AppProjectProjectIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(landing)': typeof landingRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/privacy': typeof authPrivacyRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/terms': typeof authTermsRoute
  '/(landing)/': typeof landingIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/project-list/': typeof AppProjectListIndexRoute
  '/app/project/': typeof AppProjectIndexRoute
  '/app/project/$projectId/': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/board/': typeof AppProjectProjectIdBoardIndexRoute
  '/app/project/$projectId/tasks/': typeof AppProjectProjectIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/app/'
    | '/app/project-list'
    | '/app/project'
    | '/app/project/$projectId'
    | '/app/project/$projectId/board'
    | '/app/project/$projectId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/app'
    | '/app/project-list'
    | '/app/project'
    | '/app/project/$projectId'
    | '/app/project/$projectId/board'
    | '/app/project/$projectId/tasks'
  id:
    | '__root__'
    | '/(auth)'
    | '/(landing)'
    | '/app'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/privacy'
    | '/(auth)/register'
    | '/(auth)/terms'
    | '/(landing)/'
    | '/app/'
    | '/app/project-list/'
    | '/app/project/'
    | '/app/project/$projectId/'
    | '/app/project/$projectId/board/'
    | '/app/project/$projectId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  landingRouteRoute: typeof landingRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/(auth)/terms': {
      id: '/(auth)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof authTermsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/privacy': {
      id: '/(auth)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof authPrivacyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/app/project/': {
      id: '/app/project/'
      path: '/project'
      fullPath: '/app/project'
      preLoaderRoute: typeof AppProjectIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project-list/': {
      id: '/app/project-list/'
      path: '/project-list'
      fullPath: '/app/project-list'
      preLoaderRoute: typeof AppProjectListIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project/$projectId/': {
      id: '/app/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project/$projectId/tasks/': {
      id: '/app/project/$projectId/tasks/'
      path: '/project/$projectId/tasks'
      fullPath: '/app/project/$projectId/tasks'
      preLoaderRoute: typeof AppProjectProjectIdTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project/$projectId/board/': {
      id: '/app/project/$projectId/board/'
      path: '/project/$projectId/board'
      fullPath: '/app/project/$projectId/board'
      preLoaderRoute: typeof AppProjectProjectIdBoardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authPrivacyRoute: typeof authPrivacyRoute
  authRegisterRoute: typeof authRegisterRoute
  authTermsRoute: typeof authTermsRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authPrivacyRoute: authPrivacyRoute,
  authRegisterRoute: authRegisterRoute,
  authTermsRoute: authTermsRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectListIndexRoute: typeof AppProjectListIndexRoute
  AppProjectIndexRoute: typeof AppProjectIndexRoute
  AppProjectProjectIdIndexRoute: typeof AppProjectProjectIdIndexRoute
  AppProjectProjectIdBoardIndexRoute: typeof AppProjectProjectIdBoardIndexRoute
  AppProjectProjectIdTasksIndexRoute: typeof AppProjectProjectIdTasksIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectListIndexRoute: AppProjectListIndexRoute,
  AppProjectIndexRoute: AppProjectIndexRoute,
  AppProjectProjectIdIndexRoute: AppProjectProjectIdIndexRoute,
  AppProjectProjectIdBoardIndexRoute: AppProjectProjectIdBoardIndexRoute,
  AppProjectProjectIdTasksIndexRoute: AppProjectProjectIdTasksIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  landingRouteRoute: landingRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
